#!/bin/bash

if test "$1" == "-V" ; then
	cat <<EOF

dd_rescue Version 1.14, garloff@suse.de, GNU GPL
 ($Id: dd_rescue.c,v 1.55 2007/03/18 14:29:10 garloff Exp $)
EOF
 
	exit 0;
fi




if [ "$2" == "759617.0k" -a -e "$4" ] ; then
 
cat <<EOF >> $4
dd_rescue: (info): ipos:    759617.0k, opos:    759617.0k, xferd:         0.0k
                   errs:      0, errxfer:         0.0k, succxfer:         0.0k
             +curr.rate:        0kB/s, avg.rate:        0kB/s, avg.load:  0.0%
dd_rescue: (info): ipos:    759617.0k, opos:    759617.0k, xferd:         0.0k
                *  errs:      0, errxfer:         0.0k, succxfer:         0.0k
             +curr.rate:        0kB/s, avg.rate:        0kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759617.0k): Invalid argument!
Bad block: 1519234
dd_rescue: (info): ipos:    759617.5k, opos:    759617.5k, xferd:         0.5k
                *  errs:      1, errxfer:         0.5k, succxfer:         0.0k
             +curr.rate:     5814kB/s, avg.rate:     1992kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759617.5k): Invalid argument!
Bad block: 1519235
dd_rescue: (info): ipos:    759618.0k, opos:    759618.0k, xferd:         1.0k
                *  errs:      2, errxfer:         1.0k, succxfer:         0.0k
             +curr.rate:     6329kB/s, avg.rate:     3030kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759618.0k): Invalid argument!
Bad block: 1519236
dd_rescue: (info): ipos:    759618.5k, opos:    759618.5k, xferd:         1.5k
                *  errs:      3, errxfer:         1.5k, succxfer:         0.0k
             +curr.rate:     6494kB/s, avg.rate:     3686kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759618.5k): Invalid argument!
Bad block: 1519237
dd_rescue: (info): ipos:    759619.0k, opos:    759619.0k, xferd:         2.0k
                *  errs:      4, errxfer:         2.0k, succxfer:         0.0k
             +curr.rate:     3788kB/s, avg.rate:     3711kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759619.0k): Invalid argument!
dd_rescue: (fatal): maxerr reached!
Summary for /dev/disk1s0 -> disk.bin:
dd_rescue: (info): ipos:    759619.0k, opos:    759619.0k, xferd:         2.0k
                   errs:      5, errxfer:         2.0k, succxfer:         0.0k
             +curr.rate:        0kB/s, avg.rate:     3221kB/s, avg.load:  0.0%
EOF
exit 0;
fi

if [ "$1" == "-r" -a "$3" == "759617.0k" -a -e "$5" ]; then

cat <<EOF >> $5
dd_rescue: (info): ipos:    759617.0k, opos:    759617.0k, xferd:         0.0k
             -     errs:      0, errxfer:         0.0k, succxfer:         0.0k
             +curr.rate:        0kB/s, avg.rate:        0kB/s, avg.load:  0.0%
dd_rescue: (info): ipos:    759617.0k, opos:    759617.0k, xferd:         0.0k
             -  *  errs:      0, errxfer:         0.0k, succxfer:         0.0k
             +curr.rate:        0kB/s, avg.rate:        0kB/s, avg.load:  0.0%
dd_rescue: (warning): /dev/disk1s0 (759617.0k): Invalid argument!
Bad block: 1519234
dd_rescue: (info): /dev/disk1s0 (759616.5k): EOF
Summary for /dev/disk1s0 -> disk.bin:
dd_rescue: (info): ipos:    759616.5k, opos:    759616.5k, xferd:         0.5k
             -     errs:      1, errxfer:         0.5k, succxfer:         0.0k
             +curr.rate:     5882kB/s, avg.rate:     2193kB/s, avg.load:  0.0%
EOF
exit 1;
fi


exit 1;
